import path from "node:path";
import { mkdir, writeFile } from "node:fs/promises";
import { and, eq } from "drizzle-orm";
import { client, db, schema } from "./index";

const ids = {
  user: "11111111-1111-4111-8111-111111111111",
  workspace: "22222222-2222-4222-8222-222222222222",
  brand: "33333333-3333-4333-8333-333333333333",
  profile: "44444444-4444-4444-8444-444444444444",
  content: "55555555-5555-4555-8555-555555555555",
  mediaAsset: "99999999-9999-4999-8999-999999999991",
  masterMediaLink: "99999999-9999-4999-8999-999999999992",
  outputMediaLink: "99999999-9999-4999-8999-999999999993",
  publicationJob: "99999999-9999-4999-8999-999999999994",
  approval: "99999999-9999-4999-8999-999999999995",
  run: "66666666-6666-4666-8666-666666666666",
  activityLog: "88888888-8888-4888-8888-888888888888"
};

const seededMedia = {
  relativePath: "seed/demo-orchard-output.svg",
  filename: "demo-orchard-output.svg",
  mimeType: "image/svg+xml",
  altText: "Demo Orchard social post visual"
};

const variants = [
  {
    id: "77777777-7777-4777-8777-777777777771",
    platform: "instagram",
    postType: "post",
    purpose: "main",
    sortOrder: 0,
    title: "Instagram launch teaser",
    caption: "A concise visual-first draft for Instagram, ready for local review.",
    hashtags: ["orchard", "socialmedia", "localfirst"]
  },
  {
    id: "77777777-7777-4777-8777-777777777772",
    platform: "facebook",
    postType: "post",
    purpose: "main",
    sortOrder: 1,
    title: "Facebook community update",
    caption: "A community-oriented Facebook draft generated by the stub workflow.",
    hashtags: ["orchard", "planning"]
  },
  {
    id: "77777777-7777-4777-8777-777777777773",
    platform: "linkedin",
    postType: "post",
    purpose: "main",
    sortOrder: 2,
    title: "LinkedIn product skeleton note",
    caption: "A clear LinkedIn draft that frames the idea for a professional audience.",
    hashtags: ["productization", "contentops"]
  }
];

async function seed() {
  const mediaFile = await ensureSeedMediaFile();

  await db
    .insert(schema.users)
    .values({
      id: ids.user,
      email: "admin@orchard.local",
      displayName: "Local Admin",
      authProvider: "seed"
    })
    .onConflictDoUpdate({
      target: schema.users.email,
      set: { displayName: "Local Admin", authProvider: "seed" }
    });

  await db
    .insert(schema.workspaces)
    .values({ id: ids.workspace, name: "Local Orchard Workspace", slug: "local-orchard" })
    .onConflictDoUpdate({
      target: schema.workspaces.slug,
      set: { name: "Local Orchard Workspace", status: "active" }
    });

  await db
    .insert(schema.workspaceMembers)
    .values({ workspaceId: ids.workspace, userId: ids.user, role: "owner" })
    .onConflictDoNothing();

  await db
    .insert(schema.brands)
    .values({
      id: ids.brand,
      workspaceId: ids.workspace,
      name: "Demo Orchard Brand",
      slug: "demo-orchard-brand",
      websiteUrl: "https://example.com",
      defaultLanguage: "en"
    })
    .onConflictDoUpdate({
      target: [schema.brands.workspaceId, schema.brands.slug],
      set: { name: "Demo Orchard Brand", websiteUrl: "https://example.com" }
    });

  await db
    .insert(schema.brandProfiles)
    .values({
      id: ids.profile,
      brandId: ids.brand,
      description: "A demo brand used to validate the local Orchard skeleton.",
      targetAudience: "Operators and creators planning cross-platform social content.",
      productsServices: "Social media planning and publishing workflow.",
      toneOfVoice: "Warm, clear, practical",
      preferredStyle: "Concise and useful",
      contentPillars: ["workflow", "publishing outputs", "approval"],
      forbiddenPhrases: ["set and forget"],
      platformRules: {
        instagram: { caption_style: "short and visual" },
        facebook: { caption_style: "community-oriented" },
        linkedin: { caption_style: "professional and direct" }
      }
    })
    .onConflictDoUpdate({
      target: schema.brandProfiles.brandId,
      set: {
        description: "A demo brand used to validate the local Orchard skeleton.",
        targetAudience: "Operators and creators planning cross-platform social content.",
        toneOfVoice: "Warm, clear, practical"
      }
    });

  await db
    .insert(schema.contentItems)
    .values({
      id: ids.content,
      workspaceId: ids.workspace,
      brandId: ids.brand,
      createdByUserId: ids.user,
      title: "Launch the local skeleton",
      brief: "Represent one content item with three publishing outputs and a stub automation run.",
      masterContent: "Orchard is moving from audit to a local product skeleton.",
      status: "ready_for_review",
      source: "manual",
      language: "en",
      contentPillars: ["workflow", "architecture"]
    })
    .onConflictDoUpdate({
      target: schema.contentItems.id,
      set: {
        title: "Launch the local skeleton",
        brief: "Represent one content item with three publishing outputs and a stub automation run.",
        status: "active"
      }
    });

  for (const variant of variants) {
    const isPreparedPost = variant.platform === "instagram";

    await db
      .insert(schema.platformVariants)
      .values({
        id: variant.id,
        contentItemId: ids.content,
        platform: variant.platform,
        postType: variant.postType,
        purpose: variant.purpose,
        sortOrder: variant.sortOrder,
        title: variant.title,
        headline: isPreparedPost ? "Instagram: Launch the local skeleton" : null,
        caption: variant.caption,
        hashtags: variant.hashtags,
        status: isPreparedPost ? "scheduled" : "ready_for_review",
        language: "en",
        scheduledFor: isPreparedPost ? getSeedScheduleDate() : null,
        platformOptions: { generated_by: "stub" }
      })
      .onConflictDoUpdate({
        target: schema.platformVariants.id,
        set: {
          platform: variant.platform,
          postType: variant.postType,
          purpose: variant.purpose,
          sortOrder: variant.sortOrder,
          title: variant.title,
          headline: isPreparedPost ? "Instagram: Launch the local skeleton" : null,
          caption: variant.caption,
          hashtags: variant.hashtags,
          status: isPreparedPost ? "scheduled" : "ready_for_review",
          scheduledFor: isPreparedPost ? getSeedScheduleDate() : null
        }
      });
  }

  await db
    .insert(schema.mediaAssets)
    .values({
      id: ids.mediaAsset,
      workspaceId: ids.workspace,
      brandId: ids.brand,
      uploadedByUserId: ids.user,
      source: "seed",
      mediaType: "image",
      storageProvider: "local_fs",
      storagePath: seededMedia.relativePath,
      publicUrl: `/local-media/${seededMedia.relativePath}`,
      filename: seededMedia.filename,
      mimeType: seededMedia.mimeType,
      sizeBytes: mediaFile.sizeBytes,
      altText: seededMedia.altText,
      metadata: { root: mediaFile.root }
    })
    .onConflictDoUpdate({
      target: schema.mediaAssets.id,
      set: {
        storagePath: seededMedia.relativePath,
        publicUrl: `/local-media/${seededMedia.relativePath}`,
        filename: seededMedia.filename,
        mimeType: seededMedia.mimeType,
        sizeBytes: mediaFile.sizeBytes,
        altText: seededMedia.altText,
        metadata: { root: mediaFile.root }
      }
    });

  await db
    .insert(schema.contentMedia)
    .values({
      id: ids.masterMediaLink,
      contentItemId: ids.content,
      mediaAssetId: ids.mediaAsset,
      role: "primary",
      sortOrder: 0
    })
    .onConflictDoUpdate({
      target: schema.contentMedia.id,
      set: {
        mediaAssetId: ids.mediaAsset,
        role: "primary",
        sortOrder: 0
      }
    });

  await db
    .insert(schema.contentMedia)
    .values({
      id: ids.outputMediaLink,
      contentItemId: ids.content,
      platformVariantId: variants[0].id,
      mediaAssetId: ids.mediaAsset,
      platform: "instagram",
      role: "primary",
      sortOrder: 0
    })
    .onConflictDoUpdate({
      target: schema.contentMedia.id,
      set: {
        platformVariantId: variants[0].id,
        mediaAssetId: ids.mediaAsset,
        platform: "instagram",
        role: "primary",
        sortOrder: 0
      }
    });

  await db
    .insert(schema.approvals)
    .values({
      id: ids.approval,
      contentItemId: ids.content,
      platformVariantId: variants[0].id,
      requestedByUserId: ids.user,
      reviewedByUserId: ids.user,
      status: "approved",
      comment: "Seeded demo post is approved for local preview and scheduling.",
      reviewedAt: new Date()
    })
    .onConflictDoUpdate({
      target: schema.approvals.id,
      set: {
        platformVariantId: variants[0].id,
        status: "approved",
        comment: "Seeded demo post is approved for local preview and scheduling.",
        reviewedAt: new Date()
      }
    });

  await db
    .insert(schema.publicationJobs)
    .values({
      id: ids.publicationJob,
      contentItemId: ids.content,
      platformVariantId: variants[0].id,
      platform: "instagram",
      status: "scheduled",
      scheduledFor: getSeedScheduleDate(),
      createdByUserId: ids.user
    })
    .onConflictDoUpdate({
      target: schema.publicationJobs.id,
      set: {
        status: "scheduled",
        scheduledFor: getSeedScheduleDate(),
        platformVariantId: variants[0].id,
        platform: "instagram"
      }
    });

  await db
    .insert(schema.automationRuns)
    .values({
      id: ids.run,
      workspaceId: ids.workspace,
      brandId: ids.brand,
      contentItemId: ids.content,
      runType: "generate_outputs",
      provider: "app_server",
      status: "succeeded",
      input: { mode: "seed" },
      output: { outputs: variants.map((variant) => ({ platform: variant.platform, postType: variant.postType })) },
      startedAt: new Date(),
      finishedAt: new Date()
    })
    .onConflictDoUpdate({
      target: schema.automationRuns.id,
      set: {
        runType: "generate_outputs",
        output: { outputs: variants.map((variant) => ({ platform: variant.platform, postType: variant.postType })) },
        status: "succeeded"
      }
    });

  await db
    .delete(schema.activityLogs)
    .where(and(eq(schema.activityLogs.action, "seeded"), eq(schema.activityLogs.entityId, ids.content)));

  await db
    .insert(schema.activityLogs)
    .values({
      id: ids.activityLog,
      workspaceId: ids.workspace,
      brandId: ids.brand,
      actorUserId: ids.user,
      entityType: "content_item",
      entityId: ids.content,
      action: "seeded",
      message: "Seeded a local demo content item with an assigned media output and schedule intent."
    })
    .onConflictDoNothing();

  const [content] = await db.select().from(schema.contentItems).where(eq(schema.contentItems.id, ids.content));
  console.log(`Seeded Orchard workspace with content item: ${content.title}`);
}

async function ensureSeedMediaFile() {
  const root = process.env.LOCAL_MEDIA_ROOT ?? path.resolve(process.cwd(), ".local-media");
  const absolutePath = path.resolve(root, seededMedia.relativePath);
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1080" viewBox="0 0 1080 1080">
  <rect width="1080" height="1080" fill="#f7f6f2"/>
  <rect x="96" y="96" width="888" height="888" rx="48" fill="#ffffff" stroke="#dedbd1" stroke-width="8"/>
  <circle cx="540" cy="384" r="136" fill="#2f7d57"/>
  <path d="M434 608h292" stroke="#20231f" stroke-width="36" stroke-linecap="round"/>
  <path d="M374 688h332" stroke="#64685f" stroke-width="26" stroke-linecap="round"/>
  <text x="540" y="820" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="64" font-weight="700" fill="#20231f">Orchard Demo</text>
  <text x="540" y="890" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="34" fill="#64685f">prepared post with media</text>
</svg>`;

  await mkdir(path.dirname(absolutePath), { recursive: true });
  await writeFile(absolutePath, svg);

  return {
    root,
    absolutePath,
    sizeBytes: Buffer.byteLength(svg)
  };
}

function getSeedScheduleDate() {
  return new Date("2026-06-01T09:00:00.000Z");
}

seed()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await client.end();
  });
