import { and, eq } from "drizzle-orm";
import { client, db, schema } from "./index";

const ids = {
  user: "11111111-1111-4111-8111-111111111111",
  workspace: "22222222-2222-4222-8222-222222222222",
  brand: "33333333-3333-4333-8333-333333333333",
  profile: "44444444-4444-4444-8444-444444444444",
  content: "55555555-5555-4555-8555-555555555555",
  run: "66666666-6666-4666-8666-666666666666",
  activityLog: "88888888-8888-4888-8888-888888888888"
};

const variants = [
  {
    id: "77777777-7777-4777-8777-777777777771",
    platform: "instagram",
    caption: "A concise visual-first draft for Instagram, ready for local review.",
    hashtags: ["orchard", "socialmedia", "localfirst"]
  },
  {
    id: "77777777-7777-4777-8777-777777777772",
    platform: "facebook",
    caption: "A community-oriented Facebook draft generated by the stub workflow.",
    hashtags: ["orchard", "planning"]
  },
  {
    id: "77777777-7777-4777-8777-777777777773",
    platform: "linkedin",
    caption: "A clear LinkedIn draft that frames the idea for a professional audience.",
    hashtags: ["productization", "contentops"]
  }
];

async function seed() {
  await db
    .insert(schema.users)
    .values({
      id: ids.user,
      email: "admin@orchard.local",
      displayName: "Local Admin",
      authProvider: "seed"
    })
    .onConflictDoUpdate({
      target: schema.users.email,
      set: { displayName: "Local Admin", authProvider: "seed" }
    });

  await db
    .insert(schema.workspaces)
    .values({ id: ids.workspace, name: "Local Orchard Workspace", slug: "local-orchard" })
    .onConflictDoUpdate({
      target: schema.workspaces.slug,
      set: { name: "Local Orchard Workspace", status: "active" }
    });

  await db
    .insert(schema.workspaceMembers)
    .values({ workspaceId: ids.workspace, userId: ids.user, role: "owner" })
    .onConflictDoNothing();

  await db
    .insert(schema.brands)
    .values({
      id: ids.brand,
      workspaceId: ids.workspace,
      name: "Demo Orchard Brand",
      slug: "demo-orchard-brand",
      websiteUrl: "https://example.com",
      defaultLanguage: "en"
    })
    .onConflictDoUpdate({
      target: [schema.brands.workspaceId, schema.brands.slug],
      set: { name: "Demo Orchard Brand", websiteUrl: "https://example.com" }
    });

  await db
    .insert(schema.brandProfiles)
    .values({
      id: ids.profile,
      brandId: ids.brand,
      description: "A demo brand used to validate the local Orchard skeleton.",
      targetAudience: "Operators and creators planning cross-platform social content.",
      productsServices: "Social media planning and publishing workflow.",
      toneOfVoice: "Warm, clear, practical",
      preferredStyle: "Concise and useful",
      contentPillars: ["workflow", "platform variants", "approval"],
      forbiddenPhrases: ["set and forget"],
      platformRules: {
        instagram: { caption_style: "short and visual" },
        facebook: { caption_style: "community-oriented" },
        linkedin: { caption_style: "professional and direct" }
      }
    })
    .onConflictDoUpdate({
      target: schema.brandProfiles.brandId,
      set: {
        description: "A demo brand used to validate the local Orchard skeleton.",
        targetAudience: "Operators and creators planning cross-platform social content.",
        toneOfVoice: "Warm, clear, practical"
      }
    });

  await db
    .insert(schema.contentItems)
    .values({
      id: ids.content,
      workspaceId: ids.workspace,
      brandId: ids.brand,
      createdByUserId: ids.user,
      title: "Launch the local skeleton",
      brief: "Represent one content item with three platform variants and a stub automation run.",
      masterContent: "Orchard is moving from audit to a local product skeleton.",
      status: "ready_for_review",
      source: "manual",
      language: "en",
      contentPillars: ["workflow", "architecture"]
    })
    .onConflictDoUpdate({
      target: schema.contentItems.id,
      set: {
        title: "Launch the local skeleton",
        brief: "Represent one content item with three platform variants and a stub automation run.",
        status: "ready_for_review"
      }
    });

  for (const variant of variants) {
    await db
      .insert(schema.platformVariants)
      .values({
        id: variant.id,
        contentItemId: ids.content,
        platform: variant.platform,
        caption: variant.caption,
        hashtags: variant.hashtags,
        status: "ready_for_review",
        language: "en",
        platformOptions: { generated_by: "stub" }
      })
      .onConflictDoUpdate({
        target: [schema.platformVariants.contentItemId, schema.platformVariants.platform],
        set: {
          caption: variant.caption,
          hashtags: variant.hashtags,
          status: "ready_for_review"
        }
      });
  }

  await db
    .insert(schema.automationRuns)
    .values({
      id: ids.run,
      workspaceId: ids.workspace,
      brandId: ids.brand,
      contentItemId: ids.content,
      runType: "generate_variants",
      provider: "app_server",
      status: "succeeded",
      input: { mode: "seed" },
      output: { variants: variants.map((variant) => variant.platform) },
      startedAt: new Date(),
      finishedAt: new Date()
    })
    .onConflictDoNothing();

  await db
    .delete(schema.activityLogs)
    .where(and(eq(schema.activityLogs.action, "seeded"), eq(schema.activityLogs.entityId, ids.content)));

  await db
    .insert(schema.activityLogs)
    .values({
      id: ids.activityLog,
      workspaceId: ids.workspace,
      brandId: ids.brand,
      actorUserId: ids.user,
      entityType: "content_item",
      entityId: ids.content,
      action: "seeded",
      message: "Seeded a local demo content item with stub platform variants."
    })
    .onConflictDoNothing();

  const [content] = await db.select().from(schema.contentItems).where(eq(schema.contentItems.id, ids.content));
  console.log(`Seeded Orchard workspace with content item: ${content.title}`);
}

seed()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await client.end();
  });
